//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComAddBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class emp
    {
        [DisplayName("Employee ID")]
        public int ID { get; set; }
        [DisplayName("First Name")]
        [Required]
        [MaxLength(150)]
        [MinLength(1)]
        public string First { get; set; }
        [DisplayName("Last Name")]
        [Required]
        [MaxLength(150)]
        [MinLength(1)]
        public string Last { get; set; }
        [DisplayName("E-Mail")]
        [Required]
        [MaxLength(150)]
        [MinLength(1)]
        [EmailAddress]
        public string email { get; set; }
        [DisplayName("Position")]
        [MaxLength(75)]
        [MinLength(1)]
        [Required]
        public string position { get; set; }
    }
}
